api package removed, interfaces splited between dao and service
R4V88/LibraryJava pull request #1
Opened 2020-04-22 13:24 UTC by R4V88

Usunalem pakiet api. Przenioslem interfejsy dao do pakietu dao a interfejsy service do pakietu service. Czy o takie cos chodzilo z pull req? Bo w sumie to to nowosc dla mnie troche ;D

2020-04-24 07:11 UTC, sughalith commented
Tak, o coś takiego chodzilo :) Jeszcze bym zasugerowal tylko do pakietow doa i service dodac pakiet impl i tam wrzucic implementacje serwisów/dao

2020-04-24 07:14 UTC, sughalith requested changes
Do pakietow doa i service dodaj pakiet impl i tam wrzuć implementacje serwisów/dao

2020-04-24 13:41 UTC, R4V88 commented
oki, dołożone :)

2020-04-25 18:33 UTC, sughalith approved these changes

2020-04-26 07:43 UTC, merged